// <auto-generated />
using GraphQLTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQLTest.Migrations
{
    [DbContext(typeof(SWDbContext))]
    [Migration("20191118125244_StarshipTbAdd")]
    partial class StarshipTbAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphQLTest.Data.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EyeColor");

                    b.Property<string>("Gender");

                    b.Property<string>("HairColor");

                    b.Property<int>("Height");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GraphQLTest.Data.Entities.Starship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacterId");

                    b.Property<string>("Name");

                    b.Property<int>("Passengers");

                    b.Property<string>("StarshipClass");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Starships");
                });

            modelBuilder.Entity("GraphQLTest.Data.Entities.Starship", b =>
                {
                    b.HasOne("GraphQLTest.Data.Entities.Character", "Character")
                        .WithMany("Starships")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
